<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRw7sczy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRw7sczy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRw7sczy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRw7sczy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRw7sczy\appProdProjectContainer(array(
    'container.build_hash' => 'Rw7sczy',
    'container.build_id' => 'd51f017c',
    'container.build_time' => 1544095393,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRw7sczy');
